config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  resources :questions do
    resources :answers
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  validates :body, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  validates :title, :body, presence: true
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def new
		@question = Question.find( params[:question_id] )
		@answer = Answer.new
	end
	def create
		@question = Question.find( params[:question_id] )
		@answer = @question.answers.new( answer_params )
		if @answer.save
			redirect_to @question
		else
			render :new
		end
	end

	def edit
		@question = Question.find( params[:question_id] )
		@answer = @question.answers.find( params[:id] )
	end

	def update
		@question = Question.find( params[:question_id] )
		@answer = @question.answers.find( params[:id] )

		if @answer.update( answer_params )
			redirect_to @question
		else
			render :edit
		end
	end

	def destroy
    @question = Question.find( params[:question_id] )
		@answer = @question.answers.find( params[:id] )
    @answer.destroy
    redirect_to @question
  end

	private
	def answer_params
		params.require(:answer).permit(:body)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find( params[:id] )
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new( question_params ) #made up method name question_params
    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def edit
    @question = Question.find( params[:id] )
  end

  def update
    @question = Question.find( params[:id] )
    if @question.update( question_params )
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find( params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private #encapsulation (private, public, protected--diff ways of specifying how available this particular code is for the rest of the code
  #private means these things can only be accessed by this file, it's not about protecting code from humans, but from other bits of code

  def question_params
    params.require(:question).permit(:title, :body)
      #require returns question array
      #of everything being posted, work with the questions part, and allow these two things to be submitted
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_edit.html.erb
<% if @answer.errors.any? %>
<!-- .errors is an AR method -->
	<ul>
	<% @answer.errors.full_messages.each do |err| %>
			<li><%= err %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for [@question, @answer] do |f| %>
	<% f.label :body %>
	<%= f.text_field :body %>
	<%= f.submit %>
<% end %>

app/views/answers/edit.html.erb
<p>Edit</p>
<%= render 'edit' %>

app/views/answers/new.html.erb
<%= form_for [@question, @answer] do |f| %>
	<% f.label :body %>
	<%= f.text_field :body %>
	<!-- <%= f.label :question_id %>
	<%= f.text_field :question_id %> -->
	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snackoverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">
    <header>
      <h1><%= link_to 'Snack Overflow', root_path %></h1>
    </header>
    <%= yield %>
  </div>
</body>
</html>

app/views/questions/_form.html.erb
<% if @question.errors.any? %>
	<ul>
	<% @question.errors.full_messages.each do |err| %>
			<li><%= err %></li>
		<% end %>
	</ul>
<% end %>



<%= form_for @question do |f| %>
	<%= f.label :title %>
	<%= f.string :title %>
	<%= f.label :body %>
	<%= f.text_area :body %>

	<%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<h2>Editing Question</h2>

<%= render 'form' %>

app/views/questions/index.html.erb
<h2>Questions</h2>

<ul>
  <li><%= link_to "Create New Question", new_question_path %></li>
<% @questions.each do |question| %>
  <!-- <li><%= link_to question.title, "/questions/" + question.id.to_s %></li> -->
  <li><%= link_to question.title, question_path( question ) %></li>
  <!-- <li><%= link_to question.title, question_path( question.id ) %>, most likely it's looking for an ID already so that's why .id isn't necessary</li> -->
<% end %>
</ul>

app/views/questions/new.html.erb
<!-- Form moved to _form.html.erb partial -->
<%= render 'form' %>

app/views/questions/show.html.erb
<h2><%= @question.title %></h2>
<p><%= @question.body %></p>
<br>
<%= link_to "Edit Question", edit_question_path( @question ) %>
<%= link_to "Delete Question", question_path( @question ), method: :delete, data: {confirm: "Are you sure?"} %>
<!-- No path in routes, because delete -->
<h3>Answers</h3>

<%= link_to 'Create New Answer', new_question_answer_path( @question ) %>


<% @question.answers.each do |answer| %>

  <div class="answer"><%= answer.body %>
    <%= link_to "Edit Answer", edit_question_answer_path( @question, answer ) %>
    <%= link_to "Delete Answer", question_answer_path( @question, answer ), method: :delete %></div>

<% end %>